language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-add-repository -y ppa:jkeiren/ppa
  - if test $CC = gcc; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo add-apt-repository -y ppa:apokluda/boost1.53
  - sudo add-apt-repository -y ppa:kalakris/cmake # CMake 2.11.2
  - sudo apt-get update -qq
  - sudo apt-get install -qq --assume-yes libjpeg-dev libtiff4-dev libpng12-dev cmake
  - sudo apt-get install -qq --assume-yes boost1.53 libhdf5-serial-dev
  - if test $CC = gcc; then sudo apt-get install -qq gcc-4.8 g++-4.8; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20; fi
  - if test $CC = gcc; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20; fi
  - if test $CC = gcc; then sudo update-alternatives --config gcc; fi
  - if test $CC = gcc; then sudo update-alternatives --config g++; fi
  - sudo sh .travis_scripts/install_vigra.sh $VIRTUAL_ENV

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - make

